apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
  namespace: roboshop
provisioner: ebs.csi.aws.com
volumeBindingMode: Immediate
parameters:
  type: io1
  iopsPerGB: "50"
  encrypted: "true"
  csi.storage.k8s.io/fstype: xfs
---
apiVersion: v1
kind: Namespace
metadata:
  name: roboshop
