apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-sc
  namespace: roboshop
spec:
  storageClassName: "ebs-sc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
