apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
      app: mongodb
      tier: db 
      project: roboshop
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 27017
    targetPort: 27017