apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-redis-pvc  # this should match with above storage class name.
  namespace: roboshop
spec:
  storageClassName: "ebs-sc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi