apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-redis-pvc
  namespace: roboshop
spec:
  storageClassName: "roboshop-dynamic-ebs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
