apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
      app: redis
      tier: db 
      project: roboshop
  ports:
  - name: redis-port
    protocol: TCP
    port: 6379
    targetPort: 6379