apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
      app: mysql
      tier: db
      project: roboshop
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306
    targetPort: 3306