apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
  labels:
    app: redis
    tier: db 
    project: roboshop
spec:
  selector:
    matchLabels:
      app: redis
      tier: db 
      project: roboshop
  serviceName: "redis"
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        tier: db 
        project: roboshop
    spec:
      containers:
      - name: redis
        image: redis
        volumeMounts:
        - name: redis
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 5Gi
      volumes:
      - name: redis
        persistantVolumeClaim: 
          claimName: ebs-redis-pvc