apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: redis
    tier: db 
    project: roboshop
spec:
  selector:
    matchLabels:
      app: redis
      tier: db 
      project: roboshop
  serviceName: "redis"
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        tier: db 
        project: roboshop
    spec:
      containers:
      - name: redis
        image: gspvsr/redis
        volumeMounts:
        - name: redis
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
      app: redis
      tier: db 
      project: roboshop
  ports:
  - name: redis-port
    protocol: TCP
    port: 6379
    targetPort: 6379